# Generated by Django 3.0.4 on 2020-03-16 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('item_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('owner', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
