# Generated by Django 3.0.4 on 2020-03-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_uuid',
            new_name='item_world_uuid',
        ),
    ]
