# Generated by Django 3.0.4 on 2020-03-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_auto_20200316_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_world_uuid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.UUIDField(),
        ),
    ]
