# Generated by Django 3.0.4 on 2020-03-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_auto_20200317_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
