# Generated by Django 3.0.4 on 2020-03-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0008_auto_20200317_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='owning_world_uuid',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_rotation',
            new_name='rotation',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_world_uuid',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner_uuid',
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.UUIDField(null=True),
        ),
    ]
