# Generated by Django 3.0.4 on 2020-03-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0009_auto_20200318_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='actor_class',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.UUIDField(default='null', null=True),
        ),
    ]
