# Generated by Django 3.0.4 on 2020-03-10 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Players.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ban_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='', max_length=256)),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Players.Player')),
            ],
        ),
    ]
